### ISSUE TITLE
List as reference in react-native-sensors

### ISSUE THREAD

**Issue by DanielMSchmidt** [agrcrobles/react-native-live-translator#1]
Hey there,

I really like your project and I would like to add it to a list in the readme of `react-native-sensors`, would this be okay for you? 

Also, if you would like to drive `react-native-sensors` forward please send me an E-Mail 👍

**Comment by agrcrobles** [comment]
Hey @DanielMSchmidt sure that looks great.

Thanks for considering it!

**Comment by agrcrobles** [comment]
Also found that `react-native-sensors` worked really well with the experience I was creating here, though I am not using the native driver for doing the transitions.

Let's be in touch! :)
