### ISSUE TITLE
Undefined is not an Object (evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by gautamtata** [agrcrobles/react-native-live-translator#3]
<Unknown>
Camera.js 88:26

I'm not sure if this is a problem with Xcode and camera permissions or something with the react-native-camera.

Trying to run it with expo

**Comment by gautamtata** [comment]
![error](https://user-images.githubusercontent.com/11814193/46755330-a66bec80-cc79-11e8-8788-c216940b8cfb.jpg)

**Comment by agrcrobles** [comment]
Hey there, thanks for reporting this issue.
it hasn't been designed to work neither on expo nor an iphone.
it was designed to work on android to be published on the playstore.

**Comment by gautamtata** [comment]
Thanks for the reply! I'll try to make it compatible with expo and ios. For some reason, expo/RNCamera don't seem to work well with each other/ Or only certain versions and RNSensors seem to be deprecated. 
Anyway Thanks and really cool project!

**Comment by agrcrobles** [comment]
Awesome! yeah, it uses react-native-camera and sensors libraries, and not sure if those ones are included in expo.
If u fork it feel free to send the link over here or a PR to the README.
wish u luck with that!
